run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
