package ecs

import (
	"context"
	"fmt"
	"strings"

	"github.com/edgenextapisdk/terraform-provider-edgenext/edgenext/connectivity"
	"github.com/edgenextapisdk/terraform-provider-edgenext/edgenext/helper"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ResourceENECSKeyPair returns the resource schema for ECS key_pair.
func ResourceENECSKeyPair() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceENECSKeyPairCreate,
		ReadContext:   resourceENECSKeyPairRead,
		UpdateContext: resourceENECSKeyPairUpdate,
		DeleteContext: resourceENECSKeyPairDelete,
		CustomizeDiff: resourceENECSKeyPairCustomizeDiff,
		Importer: &schema.ResourceImporter{
			StateContext: resourceENECSKeyPairImport,
		},
		Description: "Provides an EdgeNext ECS key_pair resource. name and public_key cannot be changed after creation.",
		Schema: map[string]*schema.Schema{
			"region": helper.RegionResourceSchema("region description"),
			"name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "Key pair name (also used as the Terraform resource id).",
			},
			"public_key": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "public_key description",
			},
			"private_key": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "Private key material when generated by the platform (create response only).",
			},
			"key_id": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "Platform numeric id of the key pair (from API field id).",
			},
			"fingerprint": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "OpenSSH-style fingerprint of the public key.",
			},
			"created_at": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Creation timestamp from the API.",
			},
			"deleted": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "Whether the key pair is marked deleted in the API.",
			},
			"deleted_at": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Deletion timestamp from the API, if any.",
			},
			"user_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Owning user id from the API.",
			},
			"updated_at": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Last update timestamp from the API.",
			},
		},
	}
}

func resourceENECSKeyPairCustomizeDiff(_ context.Context, d *schema.ResourceDiff, _ interface{}) error {
	// Skip this check during creation.
	if d.Id() == "" {
		return nil
	}
	if d.HasChange("name") {
		oldRaw, newRaw := d.GetChange("name")
		if strings.TrimSpace(fmt.Sprintf("%v", oldRaw)) != strings.TrimSpace(fmt.Sprintf("%v", newRaw)) {
			return fmt.Errorf("name cannot be modified after creation")
		}
	}
	if d.HasChange("public_key") {
		oldRaw, newRaw := d.GetChange("public_key")
		if strings.TrimSpace(fmt.Sprintf("%v", oldRaw)) != strings.TrimSpace(fmt.Sprintf("%v", newRaw)) {
			return fmt.Errorf("public_key cannot be modified after creation")
		}
	}
	return nil
}

func resourceENECSKeyPairImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	parts := strings.Split(d.Id(), "/")
	if len(parts) != 2 {
		return nil, fmt.Errorf("expected import id as region/name, got %q", d.Id())
	}
	region := helper.NormalizeRegion(parts[0])
	name := strings.TrimSpace(parts[1])
	if region == "" || name == "" {
		return nil, fmt.Errorf("expected import id as region/name, got %q", d.Id())
	}
	if err := d.Set("region", region); err != nil {
		return nil, err
	}
	if err := d.Set("name", name); err != nil {
		return nil, err
	}
	d.SetId(name)
	if diags := resourceENECSKeyPairRead(ctx, d, meta); diags.HasError() {
		errDiag := diags[0]
		if errDiag.Detail != "" {
			return nil, fmt.Errorf("%s: %s", errDiag.Summary, errDiag.Detail)
		}
		return nil, fmt.Errorf("%s", errDiag.Summary)
	}
	if d.Id() == "" {
		return nil, fmt.Errorf("key pair %q not found in region %q", name, region)
	}
	return []*schema.ResourceData{d}, nil
}

func resourceENECSKeyPairCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	client := m.(*connectivity.EdgeNextClient)
	ecsClient, err := client.ECSClient()
	if err != nil {
		return diag.FromErr(err)
	}

	req := map[string]interface{}{
		"region":     d.Get("region").(string),
		"public_key": d.Get("public_key").(string),
	}
	if n, ok := d.GetOk("name"); ok {
		req["name"] = n.(string)
	}
	var resp map[string]interface{}

	path := "/ecs/openapi/v2/keypair/create"

	err = ecsClient.Post(ctx, path, req, &resp)
	if err != nil {
		return diag.Errorf("failed to create ECS key_pair: %s", err)
	}
	payload, err := helper.ParseAPIResponseMap(resp)
	if err != nil {
		return diag.Errorf("failed to parse ECS key_pair create response: %s", err)
	}
	keyPairPayload := extractKeyPairPayload(payload)
	nameStr := d.Get("name").(string)
	if n, ok := keyPairPayload["name"].(string); ok && n != "" {
		nameStr = n
	}
	d.SetId(nameStr)
	if val, ok := keyPairPayload["public_key"]; ok {
		d.Set("public_key", val)
	}
	if val, ok := keyPairPayload["private_key"]; ok {
		d.Set("private_key", val)
	}

	return resourceENECSKeyPairRead(ctx, d, m)
}

func resourceENECSKeyPairUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	// The API only supports create/delete; there is no in-place update for name or public_key.
	// UpdateContext exists so name and public_key do not require ForceNew in the schema (SDK rule).
	if d.HasChange("name") || d.HasChange("public_key") {
		return diag.Errorf(
			"ECS key pair does not support updating name or public_key in place; destroy and recreate the resource or use terraform apply -replace",
		)
	}
	return resourceENECSKeyPairRead(ctx, d, m)
}

func resourceENECSKeyPairRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	client := m.(*connectivity.EdgeNextClient)
	ecsClient, err := client.ECSClient()
	if err != nil {
		return diag.FromErr(err)
	}

	req := map[string]interface{}{
		"region": helper.NormalizeRegion(d.Get("region").(string)),
		"name":   d.Id(),
	}
	var resp map[string]interface{}

	err = ecsClient.Post(ctx, "/ecs/openapi/v2/keypair/detail", req, &resp)
	if err != nil {
		// Only clear state on explicit not-found; other errors should fail apply/refresh.
		errMsg := strings.ToLower(err.Error())
		if strings.Contains(errMsg, "not found") || strings.Contains(errMsg, "404") {
			d.SetId("")
			return nil
		}
		return diag.Errorf("failed to read ECS key_pair: %s", err)
	}
	payload, err := helper.ParseAPIResponseMap(resp)
	if err != nil {
		return diag.Errorf("failed to parse ECS key_pair detail response: %s", err)
	}
	keyPairPayload := extractKeyPairPayload(payload)

	if name, ok := keyPairPayload["name"].(string); ok && name != "" {
		d.Set("name", name)
		d.SetId(name)
	}
	if val, ok := keyPairPayload["public_key"]; ok {
		d.Set("public_key", val)
	}
	if val, ok := keyPairPayload["private_key"]; ok {
		d.Set("private_key", val)
	}
	d.Set("key_id", helper.IntFromMap(keyPairPayload, "id"))
	d.Set("fingerprint", helper.StringFromMap(keyPairPayload, "fingerprint"))
	d.Set("created_at", helper.StringFromMap(keyPairPayload, "created_at"))
	if v, ok := keyPairPayload["deleted"]; ok {
		if b, ok := v.(bool); ok {
			d.Set("deleted", b)
		}
	}
	d.Set("deleted_at", helper.StringFromMap(keyPairPayload, "deleted_at"))
	d.Set("user_id", helper.StringFromMap(keyPairPayload, "user_id"))
	d.Set("updated_at", helper.StringFromMap(keyPairPayload, "updated_at"))

	return nil
}

func extractKeyPairPayload(payload map[string]interface{}) map[string]interface{} {
	if nested, ok := payload["keypair"].(map[string]interface{}); ok && nested != nil {
		return nested
	}
	return payload
}

func resourceENECSKeyPairDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	client := m.(*connectivity.EdgeNextClient)
	ecsClient, err := client.ECSClient()
	if err != nil {
		return diag.FromErr(err)
	}

	req := map[string]interface{}{
		"region": helper.NormalizeRegion(d.Get("region").(string)),
		"names":  []string{d.Id()},
	}
	var resp map[string]interface{}

	err = ecsClient.Post(ctx, "/ecs/openapi/v2/keypair/delete", req, &resp)
	if err != nil {
		return diag.Errorf("failed to delete ECS key_pair: %s", err)
	}
	if _, err := helper.ParseAPIResponsePayload(resp); err != nil {
		return diag.Errorf("failed to parse ECS key_pair delete response: %s", err)
	}

	return nil
}
