#!/usr/bin/env python3
"""
Generate a JSON file containing all documentation files for the preview page.
"""
import os
import json
from pathlib import Path

def get_doc_files():
    """Scan and organize all documentation files."""
    docs_dir = Path(__file__).parent / "docs"
    
    data_sources = []
    resources = []
    
    # Scan data sources
    d_dir = docs_dir / "d"
    if d_dir.exists():
        for file in sorted(d_dir.glob("*.html.markdown")):
            name = file.stem.replace(".html", "")
            data_sources.append({
                "name": name,
                "path": f"docs/d/{file.name}",
                "display_name": name.replace("_", " ")
            })
    
    # Scan resources
    r_dir = docs_dir / "r"
    if r_dir.exists():
        for file in sorted(r_dir.glob("*.html.markdown")):
            name = file.stem.replace(".html", "")
            resources.append({
                "name": name,
                "path": f"docs/r/{file.name}",
                "display_name": name.replace("_", " ")
            })
    
    # Organize by category
    categories = {
        "CDN": {"data_sources": [], "resources": []},
        "SSL": {"data_sources": [], "resources": []},
        "OSS": {"data_sources": [], "resources": []},
        "SCDN": {"data_sources": [], "resources": []},
        "SDNS": {"data_sources": [], "resources": []}
    }
    
    for ds in data_sources:
        if ds["name"].startswith("cdn_"):
            categories["CDN"]["data_sources"].append(ds)
        elif ds["name"].startswith("ssl_"):
            categories["SSL"]["data_sources"].append(ds)
        elif ds["name"].startswith("oss_"):
            categories["OSS"]["data_sources"].append(ds)
        elif ds["name"].startswith("scdn_"):
            categories["SCDN"]["data_sources"].append(ds)
        elif ds["name"].startswith("sdns_"):
            categories["SDNS"]["data_sources"].append(ds)
    
    for res in resources:
        if res["name"].startswith("cdn_"):
            categories["CDN"]["resources"].append(res)
        elif res["name"].startswith("ssl_"):
            categories["SSL"]["resources"].append(res)
        elif res["name"].startswith("oss_"):
            categories["OSS"]["resources"].append(res)
        elif res["name"].startswith("scdn_"):
            categories["SCDN"]["resources"].append(res)
        elif res["name"].startswith("sdns_"):
            categories["SDNS"]["resources"].append(res)
    
    return {
        "index": "docs/index.html.markdown",
        "categories": categories,
        "all_data_sources": data_sources,
        "all_resources": resources
    }

if __name__ == "__main__":
    doc_list = get_doc_files()
    
    # Generate JSON file
    output_file = Path(__file__).parent / "doc_list.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(doc_list, f, indent=2, ensure_ascii=False)
    
    # Generate JavaScript file for faster loading
    js_file = Path(__file__).parent / "doc_list.js"
    with open(js_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated document list\n")
        f.write("// This file is generated by generate_doc_list.py\n")
        f.write("window.DOC_LIST = ")
        json.dump(doc_list, f, ensure_ascii=False)
        f.write(";\n")
    
    print(f"Generated doc_list.json and doc_list.js with {len(doc_list['all_data_sources'])} data sources and {len(doc_list['all_resources'])} resources")
